# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findIntervalSingle <- function(U, breaks) {
    .Call('_DiceEnterprise_findIntervalSingle', PACKAGE = 'DiceEnterprise', U, breaks)
}

updateFunCpp <- function(currentState, B, U, connected, fine, P_cumsum, P_moves_list) {
    .Call('_DiceEnterprise_updateFunCpp', PACKAGE = 'DiceEnterprise', currentState, B, U, connected, fine, P_cumsum, P_moves_list)
}

CFTPCpp <- function(k, probs, connected, fine, P_cumsum, P_moves_list, monotonic, min, max, verbose) {
    .Call('_DiceEnterprise_CFTPCpp', PACKAGE = 'DiceEnterprise', k, probs, connected, fine, P_cumsum, P_moves_list, monotonic, min, max, verbose)
}

